apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql_db_host
  namespace: expense
data:
  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend
  namespace: expense
  labels:
    project: expense
    component: hpa
    tier: app
spec:
  replicas: 2
  selector:
    matchLabels:
      project: expense
      component: hpa
      tier: app
  template:
    metadata:
      labels:
        project: expense
        component: hpa
        tier: app
    spec:
      containers:
        - name: backend
          image: cekharch/backend:v1
          resources:
            requests:
              cpu: 100mi
              memory: 100Mi
            limits:
              cpu: 120mi
              memory: 120Mi
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql_db_host
                  key: DB_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: backend-srv
  namespace: expense
spec:
  selector:
    project: expense
    component: hpa
    tier: app
  ports:
    - port: 8080
      targetPort: 8080
---
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: backend
 namespace: expense
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: backend
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 15