apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:
    project: expense
    environment: dev
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      project: expense
      environment: dev
      tier: db
  template:
    metadata:
      labels:
        project: expense
        environment: dev
        tier: db
    spec:
      containers:
        - name: mysql
          image: cekharch/mysql:v1
---
apiVersion: v1
kind: Service
metadata: 
  name: mysql
  namespace: expense
  labels:
    project: expense
    environment: dev
    tier: db
spec:
  selector:
    project: expense
    environment: dev
    tier: db
  ports:  
    - port: 3306
      targetPort: 3306
